### ISSUE TITLE
error installing MACS2 from source

### ISSUE THREAD

**Issue by jpflorido** [macs3-project/MACS#113]
when trying to do
sudo python setup.py install

The following error comes up:

running install
running bdist_egg
running egg_info
writing requirements to MACS2.egg-info/requires.txt
writing MACS2.egg-info/PKG-INFO
writing top-level names to MACS2.egg-info/top_level.txt
writing dependency_links to MACS2.egg-info/dependency_links.txt
reading manifest file 'MACS2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'MANIFEST'
writing manifest file 'MACS2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'MACS2.Prob' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c MACS2/Prob.c -o build/temp.linux-x86_64-2.7/MACS2/Prob.o -w -O3 -ffast-math
x86_64-linux-gnu-gcc: error: MACS2/Prob.c: No such file or directory
x86_64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

Prob.c is not generated to be compiled...
Thanks!
Javier

**Comment by taoliu** [comment]
You don't have C source codes. MACS2 package on PYPI has all C files but the repository at Github only contains pyx files which you have to translate into C first using cython. So If you only cloned the source codes from github, you need to install Cython then run 'python setup_w_cython.py install'.

**Comment by beneon** [comment]
some how I still fail when running python setup_w_cython.py install. so I just cython every .pyx file in /MACS2 and /MACS2/IO, it's kinda dumb but worked for me.

**Comment by ernstki** [comment]
Later versions of MACS2 in the 2.1.x series seem to have removed the Cython dependency from their `setup.py`, and don't appear to include the `setup_w_cython.py` script anymore. I don't presume to know why, other than I noticed this in the release notes.

You can resolve this, and still use the existing `setup.py` script via `pip install .` or `python setup.py --install` by doing this first:

```bash
pip install 'cython<3'
```

The version specifier is required due to the issue described [here](https://github.com/scikit-learn/scikit-learn/issues/26858).

(In case you're wondering, I need to re-create an existing Python 2.7.x + MACS 2.1.4 installation in an HPC environment after the host operating system's libc was updated, after running into the problem [described here](https://gcc.gnu.org/pipermail/libc-alpha/2020-May/113820.html).)
