### ISSUE TITLE
Genome background when --nolambda is set

### ISSUE THREAD

**Issue by akramdi** [macs3-project/MACS#168]
Hi, 

In my quest to understand the fixed background used when --nolambda is set, I came across this very useful wiki about subcommands in MACS2 (https://github.com/taoliu/MACS/wiki/Advanced%3A-Call-peaks-using-MACS2-subcommands). So to my understanding, when --nolambda is set, the following genome background is used:

> The genome background
> 
> The whole genome background can be calculated as the number of control reads/genome size*fragment length, and in our example, it is 199867*254/2700000000 ~= .0188023. You don't need to run subcommands to build a genome background track since it's just a single value. 

And if no control is available, the genome background is estilmated using the IP reads, right? 

PS. I think the definition is not consistant with the numerical example, it should be:
(number of control reads* fragment lengh )/genome size

**Comment by taoliu** [comment]
Right. In the wikipage, I described the situation with control sample. When there is no control, the background should be estimated from IP.  You can just concepturally 'COPY' the IP data to make a 'CONTROL'. And in that case, you **shouldn't** estimate the _d_ background or even the _slocal_ and _llocal_ background since they will eliminate almost all of the real enrichment in IP data.  PS: I fixed the text of the definition.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
