### ISSUE TITLE
Peak Model -- Not Smooth

### ISSUE THREAD

**Issue by sklasfeld** [macs3-project/MACS#176]
I was reading the MACS paper and I noticed that the example Peaks model of the bimodal peaks on each strand have smooth peaks. What does it mean if the Rscript gives me a plot of ragged peaks?

**Comment by taoliu** [comment]
Normally, that means too few pairs have been selected to build the model, or the sequencing depth is too low so that noises are influential. Also, currently MACS2 provides another plot which was not included in the first MACS paper -- the cross-correlation figure. The current strategy of using cross-correlation (idea borrowed from SPP) to decide 'fragment length' works better than MACS version 1 while the noises are high or while the bimodal peaks plot is jaggy.

**Comment by philippadoherty** [comment]
Closing this issue as stale, due to inactivity. Please feel free to re-open this with a comment.
