### ISSUE TITLE
Q: Why is the default value of max-gap the detected read length?

### ISSUE THREAD

**Issue by angelosarmen** [macs3-project/MACS#401]
Hi,

I would like to use MACS2 for ATAC-seq. Could you please explain the reasoning behind the default value for max-gap being the detected read length (= tag size). Since tags are extended anyway, why use their original length for this?

**Comment by taoliu** [comment]
Hi @angelosarmen, `max-gap` is to decide how to merge two adjacent enriched regions into one. It's totally arbitrary. By default, it's set as the tag size since we can imagine tag size as the 'sampling interval' of the enrichment signal. On the other hand, we can consider the 'fragment length' (for extending tags) as the 'bandwidth' which corresponding to `min-len` option to decide the minimum length of peak to be reported. Both of the parameters can be tuned through command line option if necessary.
