### ISSUE TITLE
Q: peaks falling out of chromosomes after using --shift -75 --extsize 150 (So can't use bedToBigBed)

### ISSUE THREAD

**Issue by Cala3len** [macs3-project/MACS#438]
Hi all. 
I performed two calling with MACS2 on ATAC-seq paired end data. The first one with `- f BAMPE`, and the second one with `-f BED --shift -75 --extsize 150` as suggested in [the following discussion](https://github.com/macs3-project/MACS/discussions/435). 

Then i would like to convert peakfiles to bigBed format using the bedToBigBed tool from UCSC.  But in the case I use peakfiles from the `-f BED --shift -75 --extsize 150` calling, I get the following error : 

`End coordinate 81195231 bigger than chr17 size of 81195210`. 

Even if i am using the right chrom.sizes file !  This issue has already been reported on [biostars](https://www.biostars.org/p/269061/). This happens when we got peaks on chromosome edges... The use of the bedClip tool from UCSC solves this issue. But it looses some information dropping peaks or truncating it...

Have you got a better way to prevent or solve it without loosing information?

**Comment by taoliu** [comment]
When MACS extends reads, the new coordinates may pass the chromosome boundary. If you are using BED file, MACS has no way to know the chromosome boundaries so the problem is inevitable. Same as the approach I used to convert bedGraph to bigWig (https://gist.github.com/taoliu/2469050), using bedClip is essential. I don't think you lose information by truncating it.  In general, the end of chromosomes contains telomere repeats, and if you see peaks there, there are two possibilities: 1. the telomere is truly accessible in your case; 2. the repetitive nature there caused artificially high enrichment of reads. I suggest you check how the chromosome end peak overlaps with telomere repeats. If you are interested in the chromosome end accessibilities then you could simply drop them.

**Comment by Cala3len** [comment]
Thank you for your fast answer
