### ISSUE TITLE
Q: Is it ok to use --nolambda for chip-seq data with input control?

### ISSUE THREAD

**Issue by re2srm** [macs3-project/MACS#440]
Hello,

I am calling peaks on chip-seq data for a broad epigenetic mark. When I run the callpeaks command with mostly default settings and an input sample I get very few peaks (~3000). When I run the same command with input control and the --nolambda flag I get many more peaks (~15000). Looking at literature it seems 15000-20000 peaks are more consistent with what other people have found for this mark. But after reading the documentation it seems it is not a good idea to use a fixed global lambda. 

Do you have any comments on whether it is ok to use the --nolamda flag for chip-seq data which has an input control? I have seen a lot of papers use the --nolambda option especially for histone marks but they dont give a rationale for it.

Thanks

**Comment by taoliu** [comment]
Of course, you can do so. But if you are using `--nolambda` option, in fact, there is no need for control data since the global background is just a fixed number. If you still want to use control data to eliminate certain 'local' noises while calling the broad peak, try not to use `--nolambda` but to provide a loose cutoff, for example `-p 0.01` or `-p 0.05` instead of the default `-q 0.05`.

**Comment by re2srm** [comment]
Great. Thanks for the clarification.
