### ISSUE TITLE
Bug: callpeak using exact same arguments results in error on MACS3 but no error on MACS2

### ISSUE THREAD

**Issue by philyang07** [macs3-project/MACS#442]
**Describe the bug**
I tried using the `callpeak` function on the same BAM file and gsize value (the default value of 2.7e9) for both MACS2 and MACS3. However, MACS2 ran fine without an error, but MACS3 produced an error.

**To Reproduce**
`macs2 callpeak -t demux_testfastq_S1_L001_R1_001_aligned.bam -g 2.7e9 &> out2.txt`
`macs3 callpeak -t demux_testfastq_S1_L001_R1_001_aligned.bam -g 2.7e9 &> out3.txt`

**Expected behavior**
No errors when running either command

**Screenshots**
![image](https://user-images.githubusercontent.com/48355111/106106915-36067380-6181-11eb-97ce-cdada61bced3.png)
![image](https://user-images.githubusercontent.com/48355111/106106945-3f8fdb80-6181-11eb-9589-f674126bb861.png)

**System (please complete the following information):**
 - OS: Linux
 - Python version 3.6.9
 - Numpy version 1.18.2
 - MACS2 version 2.2.7.1
 - MACS3 version 3.0.0a5

**Comment by philyang07** [comment]
Hi @taoliu,

Sure, it's attached here.

[demux_testfastq_S1_L001_R1_001_aligned.zip](https://github.com/macs3-project/MACS/files/5897340/demux_testfastq_S1_L001_R1_001_aligned.zip)

**Comment by taoliu** [comment]
@philyang07 Finally figured out the problem. While number of reads is small and the genome size is big -- like in your testing case, the minimum number of reads to call a candidate peak to build the 'paired-peak model' will be 0. The current behavior is to call anything '>=' minimum number so the whole chromosome will be called. I have changed '>=' to '>' so that we won't see such a weird outcome again... (hope so). It has been fixed in a6cd078.

**Comment by taoliu** [comment]
@philyang07 Although I fixed the bug, you will still find that MACS3 can't build the model with the default setting. The main reason is that currently, MACS3 will look for the candidate peaks to build the model with a standard peak calling approach -- MACS version 2 uses a different and hard-to-interpret approach inherited from the first version of MACS. The default setting of MFOLD 5-50 now works predictably. To calculate what kind of 'candidate peaks' will be used to build the paired-peak model, the minimum read depth of the candidate is "the number of fold multiplied with 2 times of bandwidth (--bw)" multiplied with the average genome-wide coverage.  So in your case, the average coverage is 90k/2.7million~=0.03, so the lower and upper limit of the candidate peak would be 5*0.03=~0 and 50*0.03=~1. In this case, you won't get any usable candidate peaks to build the model. 

The best way to run your testing data is to assign the 'correct' genome size by using `-g`. The 'correct' genome size should be the length of the genome that can be possibly detected in this assay. Since you are only using the chr21 data, the `-g` should reflect the size of only chromosome 21. So if you use `-g 48000000` (chr21 size), you will get results from MACS3 too, although the results will be different with MACS2 due to our modification of building the paired-peak model.

**Comment by hubentu** [comment]
@philyang07 , MACS has been updated to 3.0.0a6. Please have a try. Thanks.
```
res <- callpeak("demux_testfastq_S1_L001_R1_001_aligned.bam", gsize=48000000, outdir="/tmp")
```
```
> res
macsList class
$outputs:
 /tmp/NA_model.r
 /tmp/NA_peaks.narrowPeak
 /tmp/NA_peaks.xls
 /tmp/NA_summits.bed 
$arguments: tfile, gsize, outdir 
$log:
 INFO  @ Wed, 10 Feb 2021 10:29:48: 
 # Command line: 
 # ARGUMENTS LIST:
 # name = NA
 # format = AUTO
...

```

**Comment by philyang07** [comment]
Hi @taoliu, thanks for fixing the issue and the clarification. Is there a way of programmatically calculating the effective genome size from say an input FASTA file?
