### ISSUE TITLE
Q: MACS3 is not on conda?

### ISSUE THREAD

**Issue by wesleylcai** [macs3-project/MACS#459]
It looks like MACS3 is not in the conda repository? Has it just not been added yet? I have an error when trying to install through pip (building wheel for cykhash), so I'd like to try a conda install.

**Comment by wesleylcai** [comment]
I reverted my python to 3.6 and the pip install worked, so I no longer need to try the conda install. Just a heads up, trying to install with python 3.9.1 gives an error while building the wheel for cykhash:

`error: command 'gcc' failed with exit status 1
    ----------------------------------------
    ERROR: Failed building wheel for cykhash
  Failed to build cykhash
  ERROR: Could not build wheels for cykhash which use PEP 517 and cannot be installed directly
  ----------------------------------------`

**Comment by Ruismart** [comment]
hey, I just got the same issue and took hours to get it done ... 
it might be like but basically not a python version issue because I tried py 3.6 - 3.9 but always got error info just as same as yours...    

for me, it's solved like this :   
---------------
conda create -n macs3
source activate macs3

conda install -n macs3 -c conda-forge python cykhash numpy cython \
pytest pytest-cov codecov setuptools \
gcc_linux-64 gxx_linux-64

# which pip
# pip install python-dev-tools   # may not need this 

# the key is gcc,
# the base gcc in the server not match my macs3 env,
# so install a new one in conda env,
# but the default bin name is x86_64-conda_cos-linux-gnu-gcc,
# need to build a soft link
ln -s ${conda_dir}/envs/macs3/bin/x86_64-***-linux-gnu-gcc ${conda_dir}/envs/macs3/bin/gcc

# then the main installation worked
pip install macs3

macs3 --help
--------------
just mark for others who would get this

**Comment by siduanmiao** [comment]
First you need updata conda to the new one, and you can install it using"mamba create -n  macs3  -c conda-forge -c maximinio macs3"
