### ISSUE TITLE
Q: Should I use --nolambda without no control?

### ISSUE THREAD

**Issue by 809825706** [macs3-project/MACS#467]
**Use case**

When I was going to call peaks with my H3K9me3 chipseq sample, I found that some people recommond:

> For broader peaks we recommend using --nomodel,--broad, --nolambda (if there's no control), and using the fragment size calculated on the strand cross correlation analysis.

**Describe the problem**

After looking for some imformation about the *lambda* and *bampe* , I was confused:

1. lambda seems be caculated by the control data. So, should I use `--nolambda` without no control in any other situation? i.e. TFs and H3K27ac. (the technical staff in our lab has a bad habit that many chipseq sample data has no input/IgG data!)
2. My data was Pair-end, so I  used `-f bampe`, in which the `--nomodel` and `--extsize` will be ignored. So. is `-f BAMPE --broad --broad-cutoff 0.1 --nolambda` enough for me?

**Comment by taoliu** [comment]
> 1. lambda seems be caculated by the control data. So, should I use `--nolambda` without no control in any other situation? i.e. TFs and H3K27ac. (the technical staff in our lab has a bad habit that many chipseq sample data has no input/IgG data!)

Without control, the 'lambda' or local bias is calculated from the sample data itself. While dealing with histone marks and chromatin accessibilities, this behavior will cause many broad peaks missing from the peak calling result. Therefore, `--nolambda` is recommended so that the 'lambda' value for Poisson test is fixed as the whole genome background estimated from sample data.

> 2. My data was Pair-end, so I  used `-f bampe`, in which the `--nomodel` and `--extsize` will be ignored. So. is `-f BAMPE --broad --broad-cutoff 0.1 --nolambda` enough for me?

Yes.  It should work.
