### ISSUE TITLE
Q: MACS - HMMRATAC - Index Out of Range

### ISSUE THREAD

**Issue by spirpinias** [macs3-project/MACS#559]
**Use case**
General Usage of the Method

**Describe the problem**
Running with default parameters and returning an error regarding Index out Range.

**Describe the solution you tried**
Tentative

**Additional context**
Please see attached logs. 
[HMM_RATAC_log.log](https://github.com/macs3-project/MACS/files/11273377/HMM_RATAC_log.log)

Anybody seen this error or know how to resolve it? 
Alignment files are from PE ATAC.

**Comment by spirpinias** [comment]
hey! @philippadoherty 

I cannot update the bam files I utilized. Do you have an email address that I could send them over to you?

**Comment by philippadoherty** [comment]
hi @spirpinias  
You can try emailing me (philippa.doherty@roswellpark.org), if the bam file is too large to email, can you provide a google drive or Dropbox link so we can download from the cloud?

Thanks!

**Comment by spirpinias** [comment]
@philippadoherty check your emails! Thank you for the help.

**Comment by philippadoherty** [comment]
@spirpinias got them, thank you!

**Comment by taoliu** [comment]
@spirpinias I found that in the log it says: 

`INFO  @ Wed, 19 Apr 2023 13:03:29: #  Total training regions after filtering with lower and upper cutoff: 0 `

It was caused by the fact that the upper limit to identify training regions for HMM is too low. The default is `20`. If you raise it as `-u 200`, you should be able to run the program. I need to reconsider the strategy to pick the training regions, perhaps remove the 'upper limit' or make it less stringent.

**Comment by spirpinias** [comment]
@taoliu success! It's running with Upper Limit 200.

**Comment by taoliu** [comment]
A new function `--cutoff-analysis-only` has been added to MACS3 for `macs3 hmmratac`. It will provide helpful information regarding your data, and help you decide the `-l`, `-u`, and `-c` cutoff. We will release the 3.0.0b2 soon with this change. #563

**Comment by spirpinias** [comment]
@taoliu awesome. Appreciate your time! Looking forward to using it.
