### ISSUE TITLE
Bug: BEDPE Format input for hmmratac

### ISSUE THREAD

**Issue by bcantarel** [macs3-project/MACS#596]
Thanks so much for adding the option to allow bedpe for hmmratac as a way to support CRAM -- unfortunately, when I am trying this command on a BED file, I am getting the following error 

**Describe the bug**

INFO  @ 26 Sep 2023 00:19:46: [95 MB] 
# Command line: hmmratac -i the_BEDPE_file.bed -f BEDPE -n temp
# Random seed selected as: 10151
 
INFO  @ 26 Sep 2023 00:19:46: [95 MB] #1 Read fragments from BAM file... 
Traceback (most recent call last):
  File "/opt/conda/bin/macs3", line 1026, in <module>
    main()
  File "/opt/conda/bin/macs3", line 101, in main
    run( args )
  File "/opt/conda/lib/python3.10/site-packages/MACS3/Commands/hmmratac_cmd.py", line 81, in run
    bam = BAMPEParser(options.bam_file[0], buffer_size=options.buffer_size)

**To Reproduce**
samtools view -@ 12 -1 --reference genome.fa -o file.bam file.cram
macs3 randsample -i file.bam -f BAMPE -p 100 -o the_BEDPE_file.bed
macs3 hmmratac -f BEDPE -i the_BEDPE_file.bed --outdir macs3out -n out --save-digested

**System (please complete the following information):**
 - OS: Linux
 - Python 3.10.12
 - Numpy version 1.23.5
 - macs3 3.0.0b3 (pulled from main last week)

**Comment by taoliu** [comment]
It is strange since in the main branch the line 81 of hmmratac_cmd.py is different with what you saw. You saw `bam = BAMPEParser(options.bam_file[0], buffer_size=options.buffer_size)`, but now it's https://github.com/macs3-project/MACS/blob/429f8f8b0114974b168900ba17d96467c27b550f/MACS3/Commands/hmmratac_cmd.py#L78-L85

Since this change hasn't been included in b3, could you remove MACS3 such as `pip uninstall macs3` then pull the main branch (git clone git@github.com:macs3-project/MACS.git) and install macs3 again? Sorry that we are working on finishing documentation these days and haven't included this BEDPE feature for hmmratac in a new release.

**Comment by bcantarel** [comment]
Thanks!  This worked for me!!

**Comment by taoliu** [comment]
@bcantarel  FYI, in the release 3.0.0, we have included the support of BEDPE format in `hmmratac` command.
