### ISSUE TITLE
qvalues in MACS2

### ISSUE THREAD

**Issue by MosheOlshansky** [macs3-project/MACS#77]
Two points:
1) Why is pvalue-qvalue table precomputed it I am running macs2 callpeak -p ... ?
2) Even if one asks for q-values, why pre-compute the table which takes quite long time? Isn't it easier to first compute p-values and then convert them into q-values, which should not take more than a few seconds (see p.adjust function in R)?

**Comment by taoliu** [comment]
1) Because in MACS2, p-values are adjusted to the number of total tests performed genome-wide, instead of to the number of tests for only number of 'peaks'. 
2) I made some optimization in the current new release (https://pypi.python.org/pypi/MACS2/2.1.0.20150420) so that p->q conversion will run much faster.

**Comment by MosheOlshansky** [comment]
Dear Tao,

Thank you very much for the information and the new release! Now everything is running much faster (especially after I installed the new version with --optimize 2)!
I have a question about broad peaks: first of all, does bdgbroadcall can do everything callpeak --broad does but is more flexible?
Secondly, is it true that -c (or -p or -q) determines which narrow peaks are kept and then -C (or --broad-cutoff) together with -G determine which of these narrow peaks are joined together? Is it also true that if -c is satisfied but -C is not, the corresponding narrow peaks will remain as they are in the final output?

Thank you very much for all your help,
Moshe.

**Comment by taoliu** [comment]
Hi Moshe,

1) Yes. If you can generate a score profile either p or q or fold-enrichment in bedGraph using bdgcmp, you can run bdgbroadcall manually. It's more flexible.

2) Yes. You are partially right. Actually, MACS2 broad mode will call regions, narrow and broad, separately using the -c/-C and -g/-G, then fit narrow ones into broad ones. Since -C is always a weaker cutoff than -c, and -G is always bigger than -g, if narrow call is satisfied then broad call should be satisfied as well. If there is any broad call which can't overlap with narrow call, then it will be reported as well in the final output -- check those lines in gappedPeak with blockNum == 2. A trick is used here for UCSC browser to accept this region without narrow call (or thickBlock in UCSC genome browser term) is that I 'faked' two 1bps thickBlocks at the beginning and end of broad call.

Best,
Tao

**Comment by MosheOlshansky** [comment]
Dear Tao,

Thank you very much for your explanations.
I am still a bit confused. 
First of all, if every narrow peak is also a broad peak, it should be called as such regardless of -c, so that -c should have no effect on the final list of broad peaks (but just on their composition). But this is not the case.
Secondly, what do -g and -G mean? Does it mean that two narrow peaks within less than -g bp from each other are considered as one peak (and similarly for two broad peaks within less than -G from each other)?

Thank you,
Moshe.

P.S. sorry for asking that many questions, but first of all I want to understand what MACS2 is doing and which parameters are mostly suitable for my needs and secondly I am planning to try GC correction and possibly a different estimation of background lambdas, and in order not to re-invent the will I am thinking of "cheating" MACS2 by giving it my own treatment-pileup and control_lambda files, and to do this properly I need to understand what MACS2 is doing. Of course it is always possible to look at the code but this is much harder and will never tell me what you had in mind. Please have no doubt that if my attempts are successful (seam to be useful in at least some situations)  they will be documented and made publicly available.

________________________________________
